# Define your beamline-specific devices here
[I0]
_target = "sst_base.detectors.ADCBuffer"
_group = "detectors"
_role = "intensity_detector"
prefix = "XF:07ID-BI[ADC:1-Ch:1]"
name = "I0 ADC"

[Idrain]
_target = "sst_base.detectors.ADCBuffer"
_group = "detectors"
prefix = "XF:07ID-BI[ADC:1-Ch:0]"
name="Sample Drain Current"

[IK2600]
_target = "nbs_bl.devices.ophScalar"
_group = "detectors"
prefix = "XF:07ID1{K2601B:1}RB-MeasI"
name = "K2600_current"

[Idm1]
_target = "nbs_bl.devices.ophScalar"
_group = "detectors"
prefix = "XF:07ID-BI{DM3:F4}Cur:I2-I"
name = "DM1 Photodiode"

[Idm3]
_target = "nbs_bl.devices.ophScalar"
_group = "detectors"
_defer_loading = true
prefix = "XF:07ID-BI{DM3:F4}Cur:I0-I"
name = "DM3 Photodiode"

[Idm4]
_target = "nbs_bl.devices.ophScalar"
_group = "detectors"
_defer_loading = true
prefix = "XF:07ID-BI{DM5:F4}Cur:I1-I"
name = "DM4 Photodiode"

[M4Adrain]
_target = "sst_base.detectors.ADCBuffer"
_group = "detectors"
_defer_loading = true
prefix = "XF:07ID-BI[ADC:1-Ch:2]"
name="M4A Drain Current"

[I1]
_target = "sst_base.detectors.ADCBuffer"
_group = "detectors"
prefix = "XF:07ID-BI[ADC:1-Ch:2]"
name = "I1 ADC"

[manipulator]
_target = "sst_base.manipulator.ManipulatorBuilder"
_group = "manipulators"
_role = "primary_sampleholder"
prefix = "XF:07ID1-BI{HAX-Ax:"
name = "haxpes_manipulator"

[enpostender]
_target = "haxpes.devices.energy_tender.energypos"
_defer_loading = true
_group = "source"
prefix = ""
name = "SST2 Energy"

[en]
_alias = "enpostender.energy"

[mono] 
_alias = "enpostender.mono"

[h]
_alias = "enpostender.harmonic"

[U42]
_alias = "enpostender.u42"

[gapoffset]
_alias = "enpostender.offset_gap"

[x2pitch]
_alias = "enpostender.mono.x2pitch"

[x2roll]
_alias = "enpostender.mono.x2roll"

[x2perp]
_alias = "enpostender.mono.x2perp"

[x2finepitch]
_alias = "enpostender.mono.x2finepitch"

[x2fineroll]
_alias = "enpostender.mono.x2fineroll"

[bragg]
_alias = "enpostender.mono.bragg"

[enpossoft]
_target = "sst_base.energy.EnPosFactory"
_group = "source"
_load_order = 2
prefix = ""
name = "en"

[ensoft]
_alias = "enpossoft.energy"
_group = 'motors'
_load_order = 2
_role = "energy"

[polsoft]
_alias = "enpossoft.energy"
_group = 'motors'
_load_order = 2
_role = "polarization"

[monosoft]
_alias = "enpossoft.monoen"
_load_order = 2

[hsoft]
_alias = "enpossoft.harmonic"
_load_order = 2

[undulatorgapsoft]
_alias = "enpossoft.epugap"
_load_order = 2

[epuoffset]
_alias = "enpossoft.offset_gap"
_load_order = 2

[haxslt] 
_target = "sst_base.slits.QuadSlits"
prefix = "XF:07ID2-OP{Slt:12-Ax:"
_role = "slits"
name = "HAXPES slits"
kind = "hinted"
concurrent = 1

[slt_dm1]
_target = "sst_base.slits.QuadSlits"
prefix = "XF:07ID6-OP{Slt:03-Ax:"
name = "DM1_slits"
kind = "hinted"
concurrent = 1

[ring_current]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
_role = "beam_current"
prefix = "HAXSIM:current"
name = "ring_current"

[dm1]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
prefix = "XF:07ID6-BI{Diag:01-Ax:Y}Mtr"
name = "DM1/FS03-Y"

[dm3]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
prefix = "XF:07ID3-BI{Diag:03-Ax:Y}Mtr"
name = "DM3/FS08-Y"

[dm4]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
prefix = "XF:07ID5-BI{Diag:04-Ax:Y}Mtr"
name = "DM4/FS09-Y"

[nBPM]
_target = "sst_base.motors.PrettyMotor"
_group = "motors"
prefix = "XF:07ID6-BI{BPM:1-Ax:Y}Mtr"
name = "nBPM/C Filter"

[L1]
_target = "sst_base.mirrors.FMBHexapodMirror"
_group = "mirrors"
prefix = "XF:07IDA-OP{Mir:L1"
name = "L1"
kind = "hinted"

[L2AB]
_target = "sst_base.mirrors.FMBHexapodMirror"
_group = "mirrors"
prefix = "XF:07IDA6-OP{Mir:L2AB"
name = "L2AB"
kind = "hinted"

[M4A]
_target = "sst_base.mirrors.FMBHexapodMirror"
_group = "mirrors"
prefix = "XF:07ID3-OP{Mir:M4A"
name = "M4A"
kind = "hinted"

[L2wedge]
_target = "ophyd.EpicsMotor"
_group = "motors"
prefix = "XF:07IDA6-OP{Mir:L2AB-Ax:Y2}Mtr"
name = "L2 Wedge"
kind = "hinted"

[SlitAB]
_target = "ophyd.EpicsMotor"
_group = "motors"
prefix = "XF:07ID3-OP{Slt:06-Ax:YGap}Mtr"
name = "Exit Slit AB"
kind = "hinted"

[softbeamenable]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
prefix = "XF:07ID1-CT{Bl-Ctrl}Endstn-Sel"
kind = "config"
string = true

[ring_status]
_target = "ophyd.EpicsSignalRO"
_group = "signals"
_role = "beam_status"
prefix = "HAXSIM:status"
name = "NSLS-II Status"

[psh1]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:1}"
name = "SST-2 Branch Shutter"

[psh2]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:2}"
name = "Shutter 2"

[psh4]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:4}"
name = "Shutter 4"

[psh5]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 0
closeval = 1
prefix = "XF:07IDA-PPS{PSh:5}"
name = "Shutter 5"

[FEsh1]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "FE"
openval = 0
closeval = 1
prefix = "XF:07ID-PPS{Sh:FE}"
name = "Front-End Shutter"


[gv10]
_target = "sst_base.shutters.EPS_Shutter"
_group = "gatevalves"
shutter_type = "GV"
openval = 1
closeval = 0
prefix = "XF:07IDB-VA:1{HAXPES-GV:1}"
name = "downstream GV"

[fs4]
_target = "sst_base.shutters.EPS_Shutter"
_group = "shutters"
shutter_type = "PH"
openval = 1
closeval = 0
prefix = "XF:07IDB-VA:1{FS:4A}"
name = "FS 4"

[floodgun]
_target = "haxpes.devices.floodgun.FloodGun"
prefix = "XF:07ID-EGPS:1:"
name = "FloodGun"

[sampx]
_alias = "manipulator.x"
_group = 'motors'

[sampy]
_alias = "manipulator.y"
_group = 'motors'

[sampz]
_alias = "manipulator.z"
_group = 'motors'

[sampr]
_alias = "manipulator.r"
_group = 'motors'

[eslit]
_alias = "haxslt.vsize"
_group = "motors"
